apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: pageturner
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_ENABLED: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: pageturner
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: pageturner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: docker-vm-1:5000/books-api:5
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: pageturner-secrets
          ports:
            - containerPort: 8080



