apiVersion: v1
kind: ConfigMap
metadata:
  name: client-config
  namespace: pageturner
data:
  ALLOWED_HOSTS: k3s-1
  API_URL: http://k3s-1:31002
---
apiVersion: v1
kind: Service
metadata:
  name: client 
  namespace: pageturner
spec:
  selector:
    app: client 
  type: NodePort
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 31001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: pageturner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: docker-vm-1:5000/books-client
          envFrom:
            - configMapRef:
                name: client-config


