apiVersion: v1
kind: Secret
metadata:
  name: pageturner-secrets
  namespace: pageturner
type: Opaque
stringData:
  POSTGRES_DB: books
  POSTGRES_PASSWORD: password
  POSTGRES_USER: postgres
  REDIS_PASSWORD: ""


