when:
  - event: push
    branch: main

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      skip_verify: true

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      repo: forgejo.local/lctrt/pageturner
      tags: latest,${CI_COMMIT_SHA}
      registry: forgejo.local
      context: ./books-client
      dockerfile: ./books-client/Dockerfile
      insecure: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: main
