when:
  - event: push
    branch: main

clone:
  - name: clone
    image: woodpeckerci/plugin-git
    settings:
      skip_verify: true

steps:
  - name: build-and-push-server
    image: plugins/docker
    settings:
      # repo: forgejo.local/lctrt/pageturner
      repo: docker-vm-1:5000/books-api
      tags: latest,${CI_COMMIT_SHA}
      registry: forgejo.local
      context: ./books-api
      dockerfile: ./books-api/Dockerfile
      insecure: true
      # username:
      #   from_secret: docker_username
      # password:
      #   from_secret: docker_password
      custom_args:
        - --insecure
        - --skip-tls-verify
    when:
      branch: main
  - name: build-and-push-client
    image: plugins/docker
    settings:
      # repo: forgejo.local/lctrt/pageturner
      repo: docker-vm-1:5000/books-client
      tags: latest,${CI_COMMIT_SHA}
      registry: forgejo.local
      context: ./books-client
      dockerfile: ./books-client/Dockerfile
      insecure: true
      # username:
      #   from_secret: docker_username
      # password:
      #   from_secret: docker_password
      custom_args:
        - --insecure
        - --skip-tls-verify
    when:
      branch: main
